#!/usr/bin/env bash

# send a message from a MQ service using STOMP
# By Laurent "ker2x" Laborde at http://www.overblog.com/
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

# VARIABLES
MQHOST=
MQPORT=
MQQ=
LOGIN=
PASS=

# Display usage and exit
usage() {
    echo "usage : $0 -h hostname -p port -q queuename [-U user -P password]"
exit 1
}

while getopts "h:p:q:U:P:" opt; do
    case $opt in
        h) MQHOST="$OPTARG";;
        p) MQPORT="$OPTARG";;
        q) MQQ="$OPTARG";;
        U) LOGIN="$OPTARG";;
        P) PASS="$OPTARG";;
        \:) echo "Option -$opt requires an argument."; exit 1;;
        \?) echo "Invalid option: -$OPTARG"; exit 1;;
    esac
done

# Host, port and queue name are mandatory
if [[ -z $MQHOST ]] || [[ -z $MQPORT ]] || [[ -z $MQQ ]]
then
    echo "ERROR : Host, port and queue name are mandatory"
    usage
fi

# Send message
(
  echo -ne 'CONNECT\n'
  if [[ -n $LOGIN ]]; then
      echo -ne "login:$LOGIN\n"
  fi
  if [[ -n $PASS ]]; then
      echo -ne "passcode:$PASS\n"
  fi
  echo -ne "\n\n\0"
  echo -ne "SEND\ndestination:$MQQ\n"
  echo -ne "\n"
  cat
  echo -ne "\0"
  echo -ne "DISCONNECT\n\n\0"
) | nc $MQHOST $MQPORT

# KTHXBYE
exit 0
